[[main]]
  name = "Bio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Shows"
  pageRef = "shows"
  weight = 20

[[main]]
  name = "Photos"
  pageRef = "photos"
  weight = 30

[[main]]
  name = "Music"
  pageRef = "music"
  weight = 35

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40

[[main]]
  name = "One Sheet"
  pageRef = "onesheet"
  weight = 50
